[project]
name = "crawlercm"
version = "0.1.0"
description = "project to scrape cm data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.0",
    "beautifulsoup4>=4.14.2",
    "fastapi>=0.119.0",
    "pydantic>=2.12.1",
    "pydantic-settings>=2.11.0",
]
